### ISSUE TITLE
Ability to enable and disable "stickyness"

### ISSUE THREAD

**Issue by MFlisar** [timehop/sticky-headers-recyclerview#39]
Is it possible to convert sticky headers to normal header items that just scroll of the screen like all the normal items?

**Comment by jacobtabak** [comment]
Do you want to be able to toggle it or just always have stickiness off in
your application?

**Comment by MichaelFlisar** [comment]
I would like to toggle it. My use case is, that I want to use the same adapter in two places, in one with sticky headers and in another with normal headers. So it would be nice to have this possibility.

**Comment by jacobtabak** [comment]
It's definitely possible but I don't think it's common enough of a use case
to include in the library. It should be rather easy with a small
modification to the source. I can point you in the right direction if you'd
like.

**Comment by MichaelFlisar** [comment]
Actually, I do it manually now. I use getItemViewType and add the headers to the data...

I haven't looked into your code yet, so pointing me into the right direction will definitely help me...

Btw, think of users writing their own base adapters that extends yours, they may put together their own code with libraries like yours and write a super adapter. That's actually what I do and that's why a simple switch between headers and sticky headers would be nice for me. But I understand your point of view.

**Comment by jacobtabak** [comment]
I disabled this on a branch for you so you can see how it's done.  Simply remove Math.max() and remove the `getTop()` (or `getLeft()`).  Check it out [here](https://github.com/timehop/sticky-headers-recyclerview/commit/7a965c928294849e5bb19a85d8b6f9fbe97a8359).  If you want to find a way to integrate it into the library without breaking the API we may consider merging it.

**Comment by MFlisar** [comment]
Thanks a lot, that's really nice from you
